---
version: '3'
services:
  tests:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
      - "./user_data/data:/testing/user_data/data"
    command: >
      python -m pytest -ra -vv -s --log-cli-level=info --artifacts-path=artifacts/ ${EXTRA_ARGS:-tests/}
    entrypoint: []
    working_dir: /testing
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./NostalgiaForInfinityX3.py:/freqtrade/NostalgiaForInfinityX3.py"
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list NostalgiaForInfinityX3
      --timerange ${TIMERANGE:-20230601-20230701}
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --config configs/exampleconfig.json
      --config configs/pairlist-static-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt.json
      --config configs/blacklist-${EXCHANGE:-binance}.json
