---
version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
      - "./user_data/data:/testing/user_data/data"
    command: >
      python -m pytest -n auto -ra -vv -s --log-cli-level=info --artifacts-path=artifacts/ ${EXTRA_ARGS:-tests/}
    entrypoint: []
    working_dir: /testing

  backtesting:
    image: freqtradeorg/freqtrade:stable
    container_name: ${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX3}
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --timeframe-detail 1m --cache none --breakdown week
      --config configs/exampleconfig.json --timerange ${TIMERANGE:-20230601-20230701}
      --config configs/pairlist-backtest-static-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt.json
      --config configs/blacklist-${EXCHANGE:-binance}.json

  plot-dataframe:
    image: freqtradeorg/freqtrade:stable_plot
    container_name: ${EXCHANGE:-binance}-${TRADING_MODE:-spot}-plot-dataframe
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    command: >
      plot-dataframe
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy ${STRATEGY_NAME:-NostalgiaForInfinityX3}
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --config configs/exampleconfig.json --timerange ${TIMERANGE:-20230601-20230701}
      --config configs/pairlist-backtest-static-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt.json
      --config configs/blacklist-${EXCHANGE:-binance}.json
      --indicators1 ema_200 --indicators2 rsi_14 cti_20

  backtesting-with-pairs-available-from-2021:
    image: freqtradeorg/freqtrade:stable
    container_name: ${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting-from-2021
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./tests:/freqtrade/tests"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list NostalgiaForInfinityX3
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --timeframe-detail 1m --cache none --breakdown week
      --config configs/exampleconfig.json --timerange 20210101-
      --config tests/backtests/pairs-available-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt-2021.json
      --disable-max-market-positions --dry-run-wallet 100000 --stake-amount 1000 --max-open-trades 100
      --log-file user_data/logs/backtesting-with-pairs-available-from-2021-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-${STRATEGY_NAME:-NostalgiaForInfinityX3}-${STRATEGY_VERSION:-latest}.log

  backtesting-with-pairs-available-from-2022:
    image: freqtradeorg/freqtrade:stable
    container_name: ${STRATEGY_NAME:-NostalgiaForInfinityX3}-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting-from-2022
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./tests:/freqtrade/tests"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX3}
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --timeframe-detail 1m --cache none --breakdown week
      --config configs/exampleconfig.json --timerange 20220101-
      --config tests/backtests/pairs-available-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt-2022.json
      --disable-max-market-positions --dry-run-wallet 100000 --stake-amount 1000 --max-open-trades 100
      --log-file user_data/logs/backtesting-with-pairs-available-from-2022-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-${STRATEGY_NAME:-NostalgiaForInfinityX3}-${STRATEGY_VERSION:-latest}.log

  backtesting-with-pairs-available-from-2023:
    image: freqtradeorg/freqtrade:stable
    container_name: ${STRATEGY_NAME:-NostalgiaForInfinityX3}-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting-from-2022
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./tests:/freqtrade/tests"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    entrypoint: []
    command: >
      freqtrade backtesting
        --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
        --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX3}
        --config configs/trading_mode-${TRADING_MODE:-spot}.json
        --timeframe-detail 1m --cache none --breakdown week --export signals
        --config configs/exampleconfig.json --timerange 20230101-
        --config tests/backtests/pairs-available-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt-2023.json
        --disable-max-market-positions --dry-run-wallet 100000 --stake-amount 1000 --max-open-trades 100
        --log-file user_data/logs/backtesting-with-pairs-available-from-2023-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-${STRATEGY_NAME:-NostalgiaForInfinityX3}-${STRATEGY_VERSION:-latest}.log
