---
version: '3'
services:
  tests:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
      - "./user_data/data:/testing/user_data/data"
    command: >
      python -m pytest -n auto -ra -vv -s --log-cli-level=info --artifacts-path=artifacts/ ${EXTRA_ARGS:-tests/}
    entrypoint: []
    working_dir: /testing
  backtesting:
    image: freqtradeorg/freqtrade:stable
    container_name: ${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./NostalgiaForInfinityX3.py:/freqtrade/NostalgiaForInfinityX3.py"
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX3}
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --timeframe-detail 1m --cache none --breakdown week
      --config configs/exampleconfig.json --timerange ${TIMERANGE:-20230601-20230701}
      --config configs/pairlist-backtest-static-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt.json
      --config configs/blacklist-${EXCHANGE:-binance}.json

  backtesting-with-pairs-available-from-2021:
    image: freqtradeorg/freqtrade:stable
    container_name: ${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting-from-2021
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./tests:/freqtrade/tests"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list NostalgiaForInfinityX3
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --timeframe-detail 1m --cache none --breakdown week
      --config configs/exampleconfig.json --timerange 20210101-
      --config tests/backtests/pairs-available-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt-2021.json
      --disable-max-market-positions --dry-run-wallet 100000 --stake-amount 1000 --max-open-trades 100

  backtesting-with-pairs-available-from-2022:
    image: freqtradeorg/freqtrade:stable
    container_name: ${STRATEGY_NAME:-NostalgiaForInfinityX3}-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting-from-2022
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./tests:/freqtrade/tests"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    command: >
      backtesting
      --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
      --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX3}
      --config configs/trading_mode-${TRADING_MODE:-spot}.json
      --timeframe-detail 1m --cache none --breakdown week
      --config configs/exampleconfig.json --timerange 20220101-
      --config tests/backtests/pairs-available-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt-2022.json
      --disable-max-market-positions --dry-run-wallet 100000 --stake-amount 1000 --max-open-trades 100


  backtesting-with-pairs-available-from-2023:
    image: freqtradeorg/freqtrade:stable
    container_name: ${STRATEGY_NAME:-NostalgiaForInfinityX3}-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-backtesting-from-2022
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./configs:/freqtrade/configs"
      - "./tests:/freqtrade/tests"
      - "./${STRATEGY_NAME:-NostalgiaForInfinityX3}.py:/freqtrade/${STRATEGY_NAME:-NostalgiaForInfinityX3}.py"
    entrypoint: []
    command: >
      freqtrade backtesting
        --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
        --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX3}
        --config configs/trading_mode-${TRADING_MODE:-spot}.json
        --timeframe-detail 1m --cache none --breakdown week --export signals
        --config configs/exampleconfig.json --timerange 20230501-
        --config tests/backtests/pairs-available-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt-2023.json
        --disable-max-market-positions --dry-run-wallet 100000 --stake-amount 1000 --max-open-trades 100
        --log-file user_data/logs/backtesting-with-pairs-available-from-2023-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-${STRATEGY_NAME:-NostalgiaForInfinityX3}-${STRATEGY_VERSION:-latest}.log





    # command: >
    #   backtesting
    #   --datadir /freqtrade/user_data/data/${EXCHANGE:-binance}
    #   --strategy-list ${STRATEGY_NAME:-NostalgiaForInfinityX3}
    #   --config configs/trading_mode-${TRADING_MODE:-spot}.json
    #   --timeframe-detail 1m --cache none --breakdown week
    #   --config configs/exampleconfig.json --timerange 20230101-
    #   --config tests/backtests/pairs-available-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-usdt-2023.json
    #   --disable-max-market-positions --dry-run-wallet 100000 --stake-amount 1000 --max-open-trades 100
    #   --log-file user_data/logs/backtesting-with-pairs-available-from-2023-${STRATEGY_NAME:-NostalgiaForInfinityX3}-${STRATEGY_VERSION:-latest}-${EXCHANGE:-binance}-${TRADING_MODE:-spot}-$(`date +"%Y-%m-%d"-%H%M%S`).log
