---
version: '3'
services:
  backtesting:
    image: freqtradeorg/freqtrade:develop
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityNext.py:/freqtrade/NostalgiaForInfinityNext.py"
    command: >
      backtesting
      --strategy-list NostalgiaForInfinityNext
      --timerange ${TIMERANGE:-20210601-20210701}
      --config user_data/pairlists.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data --timerange 20201201-20210701 --timeframe 5m 1h --config user_data/pairlists.json
