---
version: '3'
services:
  tests:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.tests"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
    command: >
      python -m pytest -ra -vv -s /testing
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityNext.py:/freqtrade/NostalgiaForInfinityNext.py"
    command: >
      backtesting
      --strategy-list NostalgiaForInfinityNext
      --timerange ${TIMERANGE:-20210601-20210701}
      --config user_data/pairlists.json
      --config user_data/${EXCHANGE:-binance}-usdt-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data --timerange ${START_DATE}-${END_DATE} --timeframe 5m 1h --config user_data/pairlists.json --config user_data/${EXCHANGE:-binance}-usdt-static.json
