---
version: '3'
services:
  tests:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
    command: >
      python -m pytest -ra -vv -s --log-cli-level=info --artifacts-path=artifacts/ ${EXTRA_ARGS:-tests/}
    entrypoint: []
    working_dir: /testing
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityX.py:/freqtrade/NostalgiaForInfinityX.py"
    command: >
      backtesting
      --datadir user_data/data/${EXCHANGE:-binance}
      --strategy-list NostalgiaForInfinityX
      --timerange ${TIMERANGE:-20210601-20210701}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
      --no-cache
